# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Lane for Android Firebase App Distribution"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor Production --target lib/main_production.dart --no-tree-shake-icons"
    firebase_app_distribution(
    app: "1:1031637881348:android:28e7e686771600aa221b51",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    testers: "bastawiie@gmail.com",
    release_notes: "Third Fastlane Firebase Distribution"
  )
  end
end
